apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: eventrouter-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: eventrouter
    namespace: ${NAMESPACE}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: event-reader
  rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: event-reader-binding
  subjects:
  - kind: ServiceAccount
    name: eventrouter
    namespace: ${NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: event-reader
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: eventrouter
    namespace: ${NAMESPACE}
  data:
    config.json: |-
      {
        "sink": "stdout"
      }
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eventrouter
    namespace: ${NAMESPACE}
    labels:
      component: eventrouter
      logging-infra: eventrouter
      provider: openshift
  spec:
    replicas: 1
    selector:
      matchLabels:
        component: eventrouter
        logging-infra: eventrouter
        provider: openshift
    template:
      metadata:
        labels:
          component: eventrouter
          logging-infra: eventrouter
          provider: openshift
      spec:
        serviceAccountName: eventrouter
        containers:
        - name: kube-eventrouter
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: ${CPU}
              memory: ${MEMORY}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumes:
        - name: config-volume
          configMap:
            name: eventrouter
parameters:
- name: IMAGE
  value: registry.ocp4.example.com:8443/openshift-logging/eventrouter-rhel9:v0.4
- name: CPU
  value: 100m
- name: MEMORY
  value: 128Mi
- name: NAMESPACE
  value: openshift-logging
